### ISSUE TITLE
Responsive Images

### ISSUE THREAD

**Issue by shazahm1** [Connections-Business-Directory/Connections#210]
This CSS seems to make some users happy ... the images will scale to content width within the templates.

``` css
#cn-list span.cn-image {
   width: auto !important;
   height: auto !important;
}

#cn-list span.cn-image img.photo {
   width: 100% !important;
   height: auto !important;
}
```
